"""added index to timestamps

Revision ID: 431aba2d555d
Revises: 864e9342e7f0
Create Date: 2019-04-09 15:46:45.856433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431aba2d555d'
down_revision = '864e9342e7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_humidity_temp_timestamp'), 'humidity_temp', ['timestamp'], unique=False)
    op.create_index(op.f('ix_water_timestamp'), 'water', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_timestamp'), table_name='water')
    op.drop_index(op.f('ix_humidity_temp_timestamp'), table_name='humidity_temp')
    # ### end Alembic commands ###
