"""empty message

Revision ID: cb303d20138b
Revises: 
Create Date: 2019-03-14 15:23:20.905249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb303d20138b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('snap_i', sa.Integer(), nullable=True),
    sa.Column('fertilizing_i', sa.Integer(), nullable=True),
    sa.Column('humidity_temp_i', sa.Integer(), nullable=True),
    sa.Column('water_treshold', sa.Integer(), nullable=True),
    sa.Column('water_amount', sa.Integer(), nullable=True),
    sa.Column('fertilize_amount', sa.Integer(), nullable=True),
    sa.Column('autowater', sa.Boolean(), nullable=True),
    sa.Column('autofertilize', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fertilize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_fertilized', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('humidity_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pics_date'), 'pics', ['date'], unique=False)
    op.create_index(op.f('ix_pics_path'), 'pics', ['path'], unique=True)
    op.create_table('water',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_watered', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water')
    op.drop_index(op.f('ix_pics_path'), table_name='pics')
    op.drop_index(op.f('ix_pics_date'), table_name='pics')
    op.drop_table('pics')
    op.drop_table('humidity_temp')
    op.drop_table('fertilize')
    op.drop_table('user')
    # ### end Alembic commands ###
