"""lol

Revision ID: d8eeaa18ba07
Revises: 
Create Date: 2019-04-24 15:05:34.423992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8eeaa18ba07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('snap_i', sa.Integer(), nullable=True),
    sa.Column('humidity_temp_i', sa.Integer(), nullable=True),
    sa.Column('water_amount', sa.Integer(), nullable=True),
    sa.Column('autowater', sa.Boolean(), nullable=True),
    sa.Column('fertilized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('humidity_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_humidity_temp_timestamp'), 'humidity_temp', ['timestamp'], unique=False)
    op.create_table('pics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pics_date'), 'pics', ['date'], unique=False)
    op.create_index(op.f('ix_pics_path'), 'pics', ['path'], unique=True)
    op.create_table('water',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_watered', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_timestamp'), 'water', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_timestamp'), table_name='water')
    op.drop_table('water')
    op.drop_index(op.f('ix_pics_path'), table_name='pics')
    op.drop_index(op.f('ix_pics_date'), table_name='pics')
    op.drop_table('pics')
    op.drop_index(op.f('ix_humidity_temp_timestamp'), table_name='humidity_temp')
    op.drop_table('humidity_temp')
    op.drop_table('user')
    # ### end Alembic commands ###
